name: Update File on Release

on:
  release:
    types:
      - created

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Update file with release version
        run: |
          echo "${{ github.event.release.tag_name }}" > version.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "Update version.txt with release version" || true
          git push origin ${{ github.head_ref }}
